# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from datetime import datetime

# Add source directory to path
sys.path.insert(0, os.path.abspath("../src"))

# -- Project information -----------------------------------------------------

project = "PSOD"
project_full = "Pseudo-Supervised Outlier Detection"
copyright = f"{datetime.now().year}, Diogo Ribeiro"
author = "Diogo Ribeiro"

# The version info for the project
# Use dynamic versioning if available
try:
    from psod import __version__

    version = __version__
    release = __version__
except ImportError:
    version = "0.1.0"
    release = "0.1.0"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here
extensions = [
    # Core Sphinx extensions
    "sphinx.ext.autodoc",  # Auto-generate documentation from docstrings
    "sphinx.ext.autosummary",  # Generate autodoc summaries
    "sphinx.ext.napoleon",  # Support for NumPy and Google style docstrings
    "sphinx.ext.viewcode",  # Add links to highlighted source code
    "sphinx.ext.intersphinx",  # Link to other project's documentation
    "sphinx.ext.mathjax",  # Render math via JavaScript
    "sphinx.ext.todo",  # Support for todo items
    "sphinx.ext.coverage",  # Documentation coverage checker
    "sphinx.ext.doctest",  # Test snippets in documentation
    "sphinx.ext.githubpages",  # Create .nojekyll file for GitHub Pages
    # Third-party extensions
    "sphinx_autodoc_typehints",  # Type hints support
    "sphinx_copybutton",  # Copy button for code blocks
    "sphinx_design",  # Design elements (cards, tabs, etc.)
    "myst_parser",  # Markdown support
    "nbsphinx",  # Jupyter notebook support
    "sphinx_gallery.gen_gallery",  # Example gallery
]

# Add any paths that contain templates here
templates_path = ["_templates"]

# List of patterns to exclude when looking for source files
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "**.ipynb_checkpoints",
]

# Skip notebooks in CI to avoid hard dependency on pandoc
_skip_notebooks = os.environ.get("PSOD_DOCS_SKIP_NOTEBOOKS") == "1" or os.environ.get(
    "GITHUB_ACTIONS"
) in {"1", "true", "True"} or os.environ.get("CI") in {"1", "true", "True"}
if _skip_notebooks:
    extensions = [ext for ext in extensions if ext != "nbsphinx"]
    exclude_patterns.append("**/*.ipynb")

# The suffix(es) of source filenames
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document
master_doc = "index"

# The language for content autogenerated by Sphinx
language = "en"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = "pydata_sphinx_theme"

# Theme options
html_theme_options = {
    "github_url": "https://github.com/diogoribeiro7/PSOD",  # TODO: Update
    "use_edit_page_button": True,
    "show_toc_level": 2,
    "navigation_depth": 4,
    "show_nav_level": 2,
    "collapse_navigation": False,
    "navigation_with_keys": True,
    "logo": {
        "text": project_full,
        "alt_text": project_full,
    },
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/diogoribeiro7/PSOD",  # TODO: Update
            "icon": "fab fa-github-square",
        },
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/psod/",  # TODO: Update
            "icon": "fas fa-box",
        },
    ],
    "footer_items": ["copyright", "sphinx-version"],
}

# Edit page configuration
html_context = {
    "github_user": "diogoribeiro7",  # TODO: Update
    "github_repo": "PSOD",
    "github_version": "main",
    "doc_path": "docs",
}

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ["_static"]

# Custom CSS files
html_css_files = [
    "custom.css",
]

# The name of an image file (relative to this directory) to place at the top
# of the sidebar
# html_logo = '_static/logo.png'  # TODO: Add logo

# The name of an image file (within the static path) to use as favicon
# html_favicon = '_static/favicon.ico'  # TODO: Add favicon

# If true, "Created using Sphinx" is shown in the HTML footer
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer
html_show_copyright = True

# Output file base name for HTML help builder
htmlhelp_basename = "PSODdoc"

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    "papersize": "letterpaper",
    "pointsize": "11pt",
}

# Grouping the document tree into LaTeX files
latex_documents = [
    (master_doc, "PSOD.tex", f"{project_full} Documentation", author, "manual"),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page
man_pages = [(master_doc, "psod", f"{project_full} Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files
texinfo_documents = [
    (
        master_doc,
        "PSOD",
        f"{project_full} Documentation",
        author,
        "PSOD",
        "Pseudo-Supervised Outlier Detection library.",
        "Miscellaneous",
    ),
]

# -- Extension configuration -------------------------------------------------

# -- autodoc configuration ---
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
    "inherited-members": True,
    "show-inheritance": True,
}

autodoc_typehints = "description"
autodoc_typehints_description_target = "documented"
autoclass_content = "both"  # Include both class and __init__ docstrings

# -- autosummary configuration ---
autosummary_generate = True
autosummary_imported_members = False

# -- napoleon configuration ---
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = True
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- intersphinx configuration ---
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "sklearn": ("https://scikit-learn.org/stable/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}

# -- todo configuration ---
todo_include_todos = True
todo_emit_warnings = True

# -- copybutton configuration ---
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_line_continuation_character = "\\"

# -- nbsphinx configuration ---
nbsphinx_execute = "never"  # Don't execute notebooks during build
nbsphinx_allow_errors = True
nbsphinx_timeout = 60
nbsphinx_kernel_name = "python3"

# Custom style for notebooks
nbsphinx_prolog = """
.. raw:: html

    <style>
        .nbinput .prompt,
        .nboutput .prompt {
            display: none;
        }
    </style>
"""

# -- sphinx-gallery configuration ---
sphinx_gallery_conf = {
    "examples_dirs": "../examples",  # Path to example scripts
    "gallery_dirs": "auto_examples",  # Path to generated gallery
    "filename_pattern": "/plot_",  # Pattern for example files
    "ignore_pattern": r"__init__\.py",
    "download_all_examples": False,
    "plot_gallery": True,
    "remove_config_comments": True,
    "expected_failing_examples": [],
    "show_memory": True,
    "line_numbers": False,
    "reference_url": {
        "psod": None,
    },
}

# -- MyST configuration ---
myst_enable_extensions = [
    "dollarmath",
    "amsmath",
    "deflist",
    "html_admonition",
    "html_image",
    "colon_fence",
    "smartquotes",
    "replacements",
]

myst_heading_anchors = 3

# -- Math configuration ---
mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
mathjax3_config = {
    "tex": {
        "inlineMath": [["$", "$"], ["\\(", "\\)"]],
        "displayMath": [["$$", "$$"], ["\\[", "\\]"]],
    },
}

# -- Custom configuration ---

# Linkcheck configuration
linkcheck_ignore = [
    r"http://localhost:\d+/",
]

# Nitpicky mode (warn about all missing references)
nitpicky = False

# Suppress warnings
suppress_warnings = [
    "image.nonlocal_uri",
]


# Add custom CSS
def setup(app):
    """Custom setup function."""
    app.add_css_file("custom.css")
